CREATE TYPE training_frequency AS ENUM (
  '3',
  '4',
  '5'
);

CREATE TYPE training_experience AS ENUM (
  'beg',
  'int',
  'adv'
);

CREATE TABLE cycles (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  completed BOOLEAN DEFAULT false,
  training_freq training_frequency NOT NULL,
  training_exp training_experience NOT NULL,
  injuries TEXT [],
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);