CREATE EXTENSION IF NOT EXISTS citext;
CREATE TYPE movement_type as ENUM (
  'squat',
  'bend',
  'horizontal pull',
  'horizontal press',
  'vertical pull',
  'vertical press',
  'core',
  'carry',
  'swing',
  'compound'
);

CREATE TABLE exercises (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title citext NOT NULL UNIQUE,
  tags TEXT [],
  movement movement_type NOT NULL,
  demo_url TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);