CREATE TYPE difficulty_level AS ENUM (
  'beg',
  'int',
  'adv'
);

CREATE TABLE hybrid_workouts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "desc" TEXT NOT NULL,
  difficulty difficulty_level,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);